name: autocommit-robot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  bots:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v1

      - name: "Set node"
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: "Install"
        run: npm install

      - name: "Run bash"
        run: node index.js

      - name: "Commit"
        uses: EndBug/add-and-commit@v4
        with:
          author_name: LunarDan
          author_email: 2306355159@qq.com
          message: "feat: save robot"
          add: "pictures/*"

        env:
          GITHUB_TOKEN: ${{ secrets.LUNARDAN_TOKEN }}
